# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

In [1]:
import numpy as np

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [2]:
dt = np.loadtxt("C:/Основная папка/Загрузки/minutes_n_ingredients.csv", delimiter=',', dtype=np.int32, skiprows=1)
dt[:5]

OSError: C:/Основная папка/Загрузки/minutes_n_ingredients.csv not found.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [80]:
dt_cropped = dt[:, 1:]

In [81]:
np.mean(dt_cropped, axis=0)

array([2.16010017e+04, 9.05528000e+00])

In [82]:
np.min(dt_cropped, axis=0)

array([0, 1])

In [83]:
np.max(dt_cropped, axis=0)

array([2147483647,         39])

In [84]:
np.median(dt_cropped, axis=0)

array([40.,  9.])

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [85]:
np.quantile(dt[:, 1], 0.75)

65.0

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [86]:
dt_tmp = dt[:, 1]
print(dt_tmp.size - np.count_nonzero(dt_tmp))
dt[:, 1] = np.where(dt_tmp != 0, dt_tmp, 1)
print(dt_tmp.size - np.count_nonzero(dt_tmp), dt_tmp)

479
0 [ 60  25  10 ...  65   5 140]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [87]:
dt_tmp = dt[:, 0]
dt_tmp.size, np.unique(dt_tmp).size # все id уникальны!

(100000, 100000)

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [88]:
dt_tmp = dt[:, 2]
ig = np.unique(dt_tmp)
dt_tmp.size, ig.size, ig

(100000,
 37,
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 37, 39]))

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [89]:
dt_tmp = dt[:, 2]
dt[dt_tmp <= 5]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [90]:
avg = dt[:, 2] / dt[:, 1]
np.mean(avg), np.max(avg)

(0.381174261705681, 24.0)

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [91]:
ingr = dt[:, 2]
time = dt[:, 1]
np.mean(ingr[np.argsort(time)][:-101:-1])

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [92]:
a = np.random.randint(0, dt.shape[0], 10)
list(zip(dt[a, 0], dt[a, 1], dt[a, 2]))

[(173453, 35, 10),
 (33489, 15, 11),
 (126580, 32, 10),
 (408757, 40, 10),
 (25096, 35, 9),
 (80904, 5, 7),
 (179087, 5, 5),
 (20674, 75, 6),
 (233836, 20, 7),
 (446605, 30, 14)]

In [ ]:
np.random.choice(dt, 10)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [93]:
np.mean(dt, axis=0)[2]

9.05528

In [94]:
dt_tmp = dt[:, 2]
(dt_tmp[dt_tmp < np.mean(dt, axis=0)[2]]).size / 100000

58802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [95]:
a = np.array((dt[:, 1] <= 20) * (dt[:, 2] <= 5))[:, np.newaxis]

r = np.append(dt, a, axis=1)
r

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [96]:
res = np.count_nonzero(r[:, 3]) / r[:, 3].size * 100
f'{res}%'

'9.552%'

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.